---
- op: replace
  path: /spec/source/repoURL
  value: https://github.com/Kousalya1998/infra-deployments.git
- op: replace
  path: /spec/source/targetRevision
  value: preview-preview-RHTAPWATCH-568
